//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

// 5fd3d285-0dd9-4362-8855-e0abaacd4af7
DEFINE_GUID(CLSID_PassCred, 0x749b22cd, 0xf9fb, 0x49bc, 0xb5, 0xad, 0xce, 0xbc, 0xb4, 0x80, 0x0a, 0x0d);